[default]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*codespell:ignore\\s*$"]

[default.extend-words]
fo = 'fo'
froms = 'froms'
selectin = 'selectin'

[files]
extend-exclude = ["docs/changelog.rst", '/examples/us_state_lookup.json', 'advanced_alchemy/types/file_object/file.py']
